nome = input('informe seu nome:')
idade = input('informe sua idade:')
data_de_aniversario = input('informe a sua data de aniversario:')
endereço = input('informe seu endereço completo,rua:')
endereço2 = input('numero da residencia:')
endereço3 = input('bairro:')
dic ={}
dic.update(nome_pe ='nome')
dic.update(idade_pe= 'idade')
dic.update(data_de_aniversario_pe = 'data_de_aniversario')
dic.update(endereço_pe = 'endereço')
dic.update(endereço2_pe = 'endereço2')
dic.update(endereço3_pe ='endereço3')
print(dic)